JWT_FILENAME = "dafni_jwt.txt"
JWT_COOKIE = "__Secure-dafnijwt"

INPUT_TITLE_HEADER = "Title"
INPUT_TYPE_HEADER = "Type"
INPUT_MIN_HEADER = "Min"
INPUT_MAX_HEADER = "Max"
INPUT_DEFAULT_HEADER = "Default"
INPUT_DESCRIPTION_HEADER = "Description"

INPUT_TYPE_COLUMN_WIDTH = 10
INPUT_MIN_MAX_COLUMN_WIDTH = 10
INPUT_DESCRIPTION_LINE_WIDTH = 20

OUTPUT_NAME_HEADER = "Name"
OUTPUT_FORMAT_HEADER = "Format"
OUTPUT_SUMMARY_HEADER = "Summary"

OUTPUT_FORMAT_COLUMN_WIDTH = 10
OUTPUT_SUMMARY_COLUMN_WIDTH = 20

CONSOLE_WIDTH = 120
