JWT_FILENAME = 'dafni_jwt.txt'
JWT_COOKIE = '__Secure-dafnijwt'

INPUT_TITLE_HEADER = "Title"
INPUT_TYPE_HEADER = "Type"
INPUT_MIN_HEADER = "Min"
INPUT_MAX_HEADER = "Max"
INPUT_DEFAULT_HEADER = "Default"
INPUT_DESCRIPTION_HEADER = "Description"

INPUT_TYPE_COLUMN_WIDTH = 10
INPUT_MIN_MAX_COLUMN_WIDTH = 10
INPUT_DESCRIPTION_LINE_WIDTH = 20
