MODELS_API_URL = "https://dafni-nims-api.secure.dafni.rl.ac.uk"
LOGIN_API_URL = "https://login.secure.dafni.rl.ac.uk"
DATA_UPLOAD_API_URL = "https://dafni-nid-api.secure.dafni.rl.ac.uk"
DISCOVERY_API_URL = "https://dafni-search-and-discovery-api.secure.dafni.rl.ac.uk"
DSS_API_URL = "https://dafni-dss-dssauth.secure.dafni.rl.ac.uk"
