name: Build Python Package

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build wheel
        run: |
          python -m build
      - name: Test wheel
        # Remove local folder to ensure testing on installed package
        run: |
          rm -r dafni_cli
          pip install ./dist/dafni_cli-*.whl
          python -m unittest discover dafni_cli.tests
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
  draft_release:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Create draft release
        run: >
          gh release create --draft --repo ${{ github.repository }}
          ${{ github.ref_name }}
          artifact/*
        env:
          GH_TOKEN: ${{ github.token }}