name: Build Python Package

# Temporary just to check the build works as expected
on:
  push:
      branches:
      - '**'
  pull_request:
      branches:
      - main
      types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build wheel
        run: |
          python -m build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*